# Generated by Django 5.1.1 on 2024-09-19 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CachedAudio',
            fields=[
                ('yt_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('thumbnail', models.URLField()),
                ('channel', models.CharField(max_length=100)),
                ('file', models.FileField(null=True, upload_to='audio/')),
            ],
        ),
    ]
