# Generated by Django 5.1.1 on 2024-09-22 01:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=25)),
                ('password', models.CharField(max_length=100)),
                ('saved_amount', models.IntegerField(default=0)),
                ('downloads_reset', models.DateTimeField(auto_now_add=True)),
                ('downloads_count', models.IntegerField(default=0)),
                ('special', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='CachedAudio',
            fields=[
                ('yt_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('thumbnail', models.URLField()),
                ('channel', models.CharField(max_length=100)),
                ('file', models.FileField(null=True, upload_to='audio/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AccountAudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='youtubent.account')),
                ('audio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='youtubent.cachedaudio')),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=100)),
                ('expire', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='youtubent.account')),
            ],
        ),
    ]
