# Generated by Django 5.1.1 on 2024-09-18 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CachedAudio',
            fields=[
                ('yt_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='audio/')),
                ('title', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
