# Generated by Django 5.1.1 on 2024-09-19 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtubent', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=25)),
                ('password', models.CharField(max_length=100)),
                ('saved', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='AccountAudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='youtubent.account')),
                ('audio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='youtubent.cachedaudio')),
            ],
        ),
    ]
