# Generated by Django 5.1.1 on 2024-09-19 18:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtubent', '0002_account_accountaudio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='saved',
        ),
        migrations.AddField(
            model_name='account',
            name='saved_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=100)),
                ('expire', models.DateTimeField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='youtubent.account')),
            ],
        ),
    ]
